# Change these first
owner: giddens9527 # Your GitHub username
repo: uptown_funk # Your GitHub repository name

# Add your sites here
sites:
  - name: Desty Official Site
    url: https://www.desty.app
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /uptown_funk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Desty
  introTitle: ""
  introMessage: Downtime monitoring for Desty
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
